<?xml version="1.0" encoding="UTF-8"?>
<!-- La plupart de ce fichier a été généré automatiquement par IntelliJ et a été modifié pour ajouter les dépendances et modifier
certaines valeurs de versions.-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.prototype</groupId>
    <artifactId>prototype2</artifactId>
    <version>1</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <!-- Tiré de https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin/0.8.12 -->
        <dependency>
            <groupId>org.jacoco</groupId>
            <artifactId>jacoco-maven-plugin</artifactId>
            <version>0.8.12</version>
        </dependency>

        <!-- Tiré de https://mvnrepository.com/artifact/org.slf4j/slf4j-nop/2.0.16 -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>2.0.16</version>
        </dependency>

        <dependency>
            <!-- Tiré de https://mvnrepository.com/artifact/org.json/json/20240303 -->
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20240303</version>
        </dependency>
            <!-- Tiré de https://mvnrepository.com/artifact/com.password4j/password4j/1.8.2 -->
        <dependency>
            <groupId>com.password4j</groupId>
            <artifactId>password4j</artifactId>
            <version>1.8.2</version>
        </dependency>

        <dependency>
            <!-- Tiré de https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api/5.11.3 -->
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.11.3</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <!-- Le code pour inclure le plugin Jacoco a été tiré de ici https://github.com/BeginSecure/JaCoCoTesting/blob/master/pom.xml -->
            <!-- Source: BeginSecure. (2023, 22 octobre). JaCoCoTesting/pom.xml. GitHub. https://github.com/BeginSecure/JaCoCoTesting/blob/master/pom.xml.-->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.10</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>

                    <execution>
                        <id>jacoco-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <rule>
                                    <element>PACKAGE</element>
                                    <limits>
                                        <limit>
                                            <counter>LINE</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.9</minimum>
                                        </limit>
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <!-- Tiré de https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin/3.4.2 -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>org.prototype.MaVille</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <!-- Tiré de https://maven.apache.org/plugins/maven-shade-plugin/usage.html -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M7</version> <!-- Use the latest version -->
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                    </includes>
                </configuration>
            </plugin>


        </plugins>

    </build>
</project>