<?xml version="1.0" encoding="UTF-8"?>
<!-- La plupart de ce fichier a été généré automatiquement par IntelliJ et a été modifié pour ajouter les dépendances et modifier
certaines valeurs de versions.-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.prototype</groupId>
    <artifactId>prototype2</artifactId>
    <version>1</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <dependency>
            <!-- Tiré de https://mvnrepository.com/artifact/org.json/json/20240303 -->
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20240303</version>
        </dependency>

        <dependency>
            <!-- Tiré de https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api/5.11.3 -->
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.11.3</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <!-- Tiré de https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin/3.4.2 -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
            </plugin>

            <plugin>
                <!-- Tiré de https://maven.apache.org/plugins/maven-shade-plugin/usage.html -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>
</project>